### ISSUE TITLE
CKR_USER_NOT_LOGGED_IN - Inspite of correct PIN

### ISSUE THREAD

**Issue by supreetd21** [LudovicRousseau/PyKCS11#61]
#### Your system information

* Operating system used:
MacOS Mojave 10.14.4

* PyKCS11 version:
1.5.5

* Python version:
Python 2.7.10

* PKCS#11 library used:
/Library/OpenSC/lib/opensc-pkcs11.so

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen.

I am trying to sign my CSR using a YubiKey 5.
On executing samples/getinfo.py. I get the following result.
```
cryptokiVersion: 2.20
flags:
libraryDescription: OpenSC smartcard framework
libraryVersion: 0.19
manufacturerID: OpenSC Project
Available Slots: 1 [0]

Slot 1/1 (number 0):
 firmwareVersion: 0.00
 flags: CKF_TOKEN_PRESENT, CKF_REMOVABLE_DEVICE, CKF_HW_SLOT
 hardwareVersion: 5.18
 manufacturerID: Yubico
 slotDescription: Yubico Yubikey 4 OTP+U2F+CCID
 SessionInfo
  flags: CKF_SERIAL_SESSION
  slotID: 0
  state: CKS_RO_PUBLIC_SESSION
  ulDeviceError: 0
 TokenInfo
  firmwareVersion: 0.0
  flags: CKF_RNG, CKF_LOGIN_REQUIRED, CKF_TOKEN_INITIALIZED, CKF_USER_PIN_INITIALIZED
  hardwareVersion: 0.0
  label: supreetdeshpande
  manufacturerID: piv_II
  model: PKCS#15 emulated
  serialNumber: 9bf84dc101dab7f7
  ulFreePrivateMemory: -1
  ulFreePublicMemory: -1
  ulMaxPinLen: 8
  ulMaxRwSessionCount: 0
  ulMaxSessionCount: 0
  ulMinPinLen: 4
  ulRwSessionCount: 0
  ulSessionCount: 0
  ulTotalPrivateMemory: -1
  ulTotalPublicMemory: -1
  utcTime:
```

#### Steps for reproducing this issue:
On executing signature.py (I have added my Private Key into the PIV slot for the Yubikey through their GUI tool)
I get the following error:
`Traceback (most recent call last):
  File "signature.py", line 40, in <module>
    signature = session.sign(privKey, binascii.unhexlify(toSign), mechanism)
  File "/Library/Python/2.7/site-packages/PyKCS11/__init__.py", line 1086, in sign
    raise PyKCS11Error(rv)
PyKCS11.PyKCS11Error: CKR_USER_NOT_LOGGED_IN (0x00000101)`

CKR_USER_NOT_LOGGED_IN -I have given the correct PIN as the samples/getinfo.py worked well.
Could you help me with the usual reason for such an error?
